# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: /data/projects/tbx3/local/share/data/metadata_dhd1_samples
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

# what if there are more units to a single sample? shouldn't they be merged prior to counting??
units: /data/projects/tbx3/local/share/data/units_dhd1.tsv

fq_files: /data/projects/tbx3/local/share/data/metadata_dhd1_files

#input_folder: /IMCR_shares/Moorlab/simo/170714_NB501465_0132_AH25MKBGX3/dhd1/

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  # from https://international.neb.com/faqs/2018/04/19/how-should-the-adaptor-sequences-be-trimmed -> NEBNext Template Switching Oligo -> GCTAATCATTGCAAGCAGTGGTATCAACGCAGAGTACAT
  adapter: AGATCGGAAGAG
#ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "/data/references/gencode/mmusculus/STAR"
  # gtf file with transcripts
  annotation: "/data/references/gencode/mmusculus/gencode.vM24.basic.annotation.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
        # contrasts for the deseq2 results method # initial comparison: hem_dhd1 vs exp_dhd1
  contrasts:
    hem-vs-exp:
      - hem
      - exp

params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""
